services:
  db:
    container_name: mysql_server
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_USERNAME=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306